### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by profishional** [Anish-Agnihotri/friendmex#1]
This is awesome Anish, Nostalgic, and fun!
Thank you.

Could you create a search function so we can find users?

🙏

**Comment by proofofjake** [comment]
PLEASE FOR THW LOVE OF GOD ADD THIS

**Comment by profishional** [comment]
Wow, I see the feature now. 
Thank you @Anish-Agnihotri!

**Comment by profishional** [comment]
Wow, I see the feature now.
Thank you @Anish-Agnihotri!
