### ISSUE TITLE
[bug] Chart doesn't update

### ISSUE THREAD

**Issue by profishional** [Anish-Agnihotri/friendmex#3]
One more thing. I'm not sure if this is from my end but some charts don't seem to update:
<img width="1508" alt="image" src="https://github.com/Anish-Agnihotri/friendmex/assets/93366432/4c62ffd1-2181-4501-b961-d1985c5ed8f0">

tried
- hard refresh
- clearing cookies

@Anish-Agnihotri

**Comment by Anish-Agnihotri** [comment]
Thanks; this should be fixed.
