### ISSUE TITLE
Redirect to person twitter profile after clicking on @ header

### ISSUE THREAD

**Issue by gardnertechhq** [Anish-Agnihotri/friendmex#6]
**FEATURE REQUEST**
-----------------------------------------------------------------------------------------------------------------------------------------------
The idea is to have build in redirection to twitter profile after clicking user name to distinguish them from scammers in handy way.

**Comment by Anish-Agnihotri** [comment]
This already exists if you click on the handles in the user cards.

https://github.com/Anish-Agnihotri/friendmex/assets/4398624/9ca43aad-f580-43be-8834-11846d439067

his already exists if you
